### ISSUE TITLE
Improve Helm Chart Accessibility and Discoverability

### ISSUE THREAD

**Issue by guillheu** [jellyfin/jellyfin-helm#17]
Currently, using this chart is more difficult than it has to be, since it is not being served by a proper helm chart repository (as far as I can tell).

Ideally, the helm release workflow should package the main branch's charts and create/update an `index.yaml` file and push those changes to the `gh-pages` branch.
I've noticed you have included the [helm release workflow](https://helm.sh/docs/howto/chart_releaser_action/#helm), but haven't created a `gh-pages` branch for it to push to. By creating a `gh-pages` branch and enabling github pages to serve the root directory of the `gh-pages` branch, the helm chart would be easily accessible at `https://jellyfin.github.io/jellyfin-helm`, making it way simpler to use the chart.
After that, I think it'd be good to list the chart on artifacthub.io. The process shouldn't take long and will make the chart far more discoverable.

**Comment by mikepjb** [comment]
Thanks @guillheu - reading this allowed me to set this up using helmfile.

Just including `https://jellyfin.github.io/jellyfin-helm` on the README.md would be a really nice improvement to the project, it seems that gh-pages is being used.
