### ISSUE TITLE
Release 1.4.0 broke the chart

### ISSUE THREAD

**Issue by Supporterino** [jellyfin/jellyfin-helm#37]
Hi @crobibero,

it seems like the last [release workflow](https://github.com/jellyfin/jellyfin-helm/actions/runs/11672609047) wasn't run with the correct jellyfin container version as input but with the new chart version as input which brakes the app since it tries to pull jellyfin version `1.4.0`

**Comment by crobibero** [comment]
Oops yeah I totally put `1.4.0` instead of `10.10.1`
I've pushed a new `1.5.0` that references `10.10.1`
