### ISSUE TITLE
horizontal scaling

### ISSUE THREAD

**Issue by lknite** [jellyfin/jellyfin-helm#42]
If deploying via a kubernetes cluster does Jellyfin itself scale or is it possible to spin up a pod to perform transcoding?

(Doing some research before deploying.  I don't see any scaling options in the helm chart.)

**Comment by crobibero** [comment]
No, Jellyfin does not support horizontal scaling.
You may be able to use [rffmpeg](https://github.com/joshuaboniface/rffmpeg/)

**Comment by lknite** [comment]
I pretty much just assumed the answer was no, but is there no discussion for it?  Seems like there'd be a little community working on ensuring it gets in there over time.  No?  Maybe some direction towards such a group?

**Comment by lknite** [comment]
does it support horizontal scaling now?
